(* ::Package:: *)

(* ::Input:: *)
(*MonteCarloPi[n_]:=Module[{count,x,y,distance},count=0;*)
(*Do[x=RandomReal[];*)
(*y=RandomReal[];*)
(*distance=x^2+y^2;*)
(*If[distance<=1,count++];,{n}];*)
(*4.0 count/n]*)
(**)
